spring:
  profiles:
    active: jpa
  flyway:
    enabled: false

invoicing-system:
  database: jpa
  database.directory: db
  database.invoices.file: invoices.txt
  database.id.file: id.txt

logging:
  level:
    org:
      springframework:
        boot: INFO

    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG




