server:
  port: 8080

spring:
  profiles:
    active: file
  flyway:
    enabled: true
  security:
    user:
      name: jonatan
      password: haslo

invoicing-system:
  database: file
  database.directory: db
  database.invoices.file: invoices.txt
  database.companies.file: companies.txt
  database.id.file: id.txt
  allowedOrigins: http://localhost:4200
  csrf:
    disable: true

logging:
  level:
    org:
      springframework:
        boot: INFO

    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG




