server:
  port: 8080

spring:
  profiles:
    active: jpa
  flyway:
    enabled: true

invoicing-system:
  database: memory
  database.directory: db
  database.invoices.file: invoices.txt
  database.companies.file: companies.txt
  database.id.file: id.txt

logging:
  level:
    org:
      springframework:
        boot: INFO

    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG




