spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/invoicing
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  main:
    allow-bean-definition-overriding: true

invoicing-system:
  database: file
  database.directory: db
  database.invoices.file: invoices.txt
  database.id.file: id.txt

logging:
  level:
    org:
      springframework:
        boot: INFO

    pl:
      futurecollars:
        invoicing: INFO
        invoicing.db: DEBUG




