/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pl.futurecollars.invocing;

public class App {
    public String getGreetings() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreetings());
    }
}
