package pl.futurecollars.invoicing.model;

import io.swagger.annotations.ApiModelProperty;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@AllArgsConstructor
@NoArgsConstructor
@Data
@Builder
@Entity
public class Car {

    @ApiModelProperty(value = "Car id (generated by application)", required = true, example = "1")
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Id
    private int id;

    @ApiModelProperty(value = "Car registration number", required = true, example = "KWI 601587")
    private String registrationNumber;

    @ApiModelProperty(value = "Specifies if car is used also for personal reasons", required = true, example = "true")
    private boolean personalUse;

}
